substitutions:
  devicename: opentherm
  upper_devicename: Opentherm

esphome:
  name: $devicename
  platform: ESP8266
  board: d1_mini
  arduino_version: '2.7.2'  
  platformio_options:
    lib_deps: 
    - ihormelnyk/OpenTherm Library @ 1.1.3
    - ESP Async WebServer
  includes:
    - esphome-opentherm/

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${devicename} Fallback"
    password: !secret esphome_fallback_password

captive_portal:
logger:
api:
ota:

custom_component:
  - lambda: |-
      auto opentherm = new OpenthermComponent();
      return {opentherm};
    
    components:
      - id: opentherm
output:
  - platform: custom
    type: float
    lambda: |-
      OpenthermComponent *openthermComp = (OpenthermComponent*) opentherm;
      return {openthermComp->pidRelativeModulationLevel};
    outputs:
      id: pidRelativeModulationLevel
      #min_power: 30.00%
      #max_power: 60.00%

dallas:
  # https://diyless.com/blog/home-assistant-opentherm-thermostat
  - pin: 14

sensor:
  - platform: custom
    lambda: |-    
      OpenthermComponent *openthermComp = (OpenthermComponent*) opentherm;
      return {
        App.register_component(openthermComp->pidRelativeModulationLevel),
        App.register_component(openthermComp->boilerRelativeModulationLevel),
        App.register_component(openthermComp->relativeModulationLevel),

        openthermComp->outside_temperature_sensor, 
        openthermComp->return_temperature_sensor, 
        openthermComp->boiler_pressure_sensor,
        openthermComp->central_heating_actual_temperature_sensor,
        openthermComp->central_heating_target_temperature_sensor
      };
    sensors:
    - name: "PID Relative Modulation Level"
    - name: "Boiler Relative Modulation Level"
    - name: "Relative Modulation Level"

    - name: "Outside Temperature"
      unit_of_measurement: °C
      accuracy_decimals: 0
      device_class: temperature
      icon: "mdi:sun-thermometer-outline"
    - name: "Return Temperature"
      unit_of_measurement: °C
      accuracy_decimals: 1
      device_class: temperature
      icon: "mdi:water-sync"
    - name: "Boiler Pressure"
      unit_of_measurement: hPa
      accuracy_decimals: 1
      device_class: pressure
      icon: "mdi:hydraulic-oil-level"
    - name: "Central Heating Actual Temperature"
      unit_of_measurement: °C
      accuracy_decimals: 1
      device_class: temperature
      icon: "mdi:water-boiler"
    - name: "Central Heating Target Temperature"
      unit_of_measurement: °C
      accuracy_decimals: 1
      device_class: temperature
      icon: "mdi:thermostat"
      
  # - platform: homeassistant
  #   id: room_temperature_sensor
  #   entity_id: sensor.room_temperature_sensor
  #   name: "Room Temperature"
  #   unit_of_measurement: °C
  #   device_class: temperature
  #   icon: "mdi:home-thermometer"

  # You may want to replace room_temperature_sensor by a room thermostat that isn't close to the boiler
  - platform: dallas
    id: room_temperature_sensor
    name: "Room Temperature"
    unit_of_measurement: °C
    device_class: temperature
    index: 0
    icon: "mdi:home-thermometer-outline"

  - platform: pid
    name: "Modulating Thermostat PID Result"
    type: RESULT
    icon: "mdi:vector-curve"
    disabled_by_default: true
  - platform: pid
    name: "Modulating Thermostat PID HEAT"
    type: HEAT
    icon: "mdi:vector-curve"
    disabled_by_default: true
  - platform: pid
    name: "Modulating Thermostat PID ERROR"
    type: ERROR
    icon: "mdi:vector-curve"
    disabled_by_default: true

binary_sensor:
  - platform: custom
    lambda: |-
      OpenthermComponent *openthermComp = (OpenthermComponent*) opentherm;
      return {
        App.register_component(openthermComp->centralHeatingMode),
        App.register_component(openthermComp->centralHeatingEnable),
        
        openthermComp->boiler_flame_sensor,
      };
    binary_sensors:
    - name: "Central Heating Mode"
    - name: "Central Heating Enable"

    - name: "Boiler Flame"
      device_class: heat

switch:
  - platform: custom
    lambda: |-
      OpenthermComponent *openthermComp = (OpenthermComponent*) opentherm;
      return {openthermComp->pidModulationSwitch};
    switches:
    - name: "PID Modulation"
  - platform: template
    name: "PID Modulation Start autotune"
    turn_on_action:
      - climate.pid.autotune: pid_controller      

climate:
  - platform: custom
    lambda: |-
      OpenthermComponent *openthermComp = (OpenthermComponent*) opentherm;
      return {
        openthermComp->domestic_hot_water_climate, 
        openthermComp->central_heating_climate
      };
    climates:
      - id: domestic_hot_water
        name: "Domestic Hot Water"
      - id: central_heating
        name: "Central Heating"
  - platform: pid
    id: pid_controller
    name: "PID Controller"
    visual:
      min_temperature: 15 °C
      max_temperature: 35 °C
      temperature_step: 0.5 °C
    sensor: room_temperature_sensor
    default_target_temperature: 20 °C
    heat_output: pidRelativeModulationLevel
    control_parameters:
      kp: 0.38197
      ki: 0.01012
      kd: 3.60387